server:
  port: 8080

datasource:
  url: "195.208.118.156:5432"
  db: auth
  user: user
  password: password

superuser:
  username: admin
  email: admin@admin.com
  password: password

jwt:
  ttl:
    access: 1
    refresh: 15
    unit: m
  secret: "super-secret-key-change-me"
